{{- if .Values.commandRouterService.enabled }}
#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "service-command-router" "name" "service-command-router-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  cache-config.xml: |
  {{- tpl ( .Files.Get "config/command-router/cache-config.xml" ) . | nindent 4 }}
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.commandRouterService.hono.app.maxInstances }}
        startupTimeout: {{ .Values.commandRouterService.hono.app.startupTimeout }}
      auth:
        {{- if .Values.commandRouterService.hono.auth }}
        {{- .Values.commandRouterService.hono.auth | toYaml | nindent 8 }}
        {{- else }}
        host: {{ printf "%s-service-auth" .Release.Name | quote }}
        port: 5671
        trustStorePath: "/etc/hono/trusted-certs.pem"
        hostnameVerificationRequired: false
        name: {{ printf "Hono %s" $args.component | quote }}
        validation:
          certPath: "/etc/hono/auth-server-cert.pem"
        {{- end }}
      registration:
        {{- .Values.commandRouterService.hono.registration | toYaml | nindent 8 }}
      command:
        {{- .Values.commandRouterService.hono.command | toYaml | nindent 8 }}
      commandRouter:
        amqp:
          {{- if .Values.commandRouterService.hono.commandRouter.amqp }}
          {{- .Values.commandRouterService.hono.commandRouter.amqp | toYaml | nindent 10 }}
          {{- else }}
          bindAddress: "0.0.0.0"
          keyPath: "/etc/hono/key.pem"
          certPath: "/etc/hono/cert.pem"
          {{- end }}
      {{- include "hono.healthServerConfig" .Values.commandRouterService.hono.healthCheck | nindent 6 }}
data:
  key.pem: {{ .Files.Get "example/certs/command-router-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "example/certs/command-router-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "example/certs/trusted-certs.pem" | b64enc }}
  auth-server-cert.pem: {{ .Files.Get "example/certs/auth-server-cert.pem" | b64enc }}
{{- end }}
